-- Retrieve the total number of orders placed.

SELECT * FROM ORDERS;
SELECT COUNT(ORDER_ID) AS TOTAL_ORDERS FROM ORDERS;

-- Calculate the total revenue generated from pizza sales.

SELECT * FROM PIZZAS;
SELECT * FROM order_details;

SELECT ROUND(SUM(order_details.QUANTITY * PIZZAS.PRICE),2) AS TOTAL_REVENUE
FROM ORDER_DETAILS
LEFT JOIN PIZZAS
ON order_details.PIZZA_ID = PIZZAS.PIZZA_ID;

-- Identify the highest-priced pizza.

SELECT PIZZA_TYPES.NAME, PIZZAS.PRICE
FROM PIZZAS
LEFT JOIN pizza_types
ON PIZZAS.PIZZA_TYPE_ID = PIZZA_TYPES.PIZZA_TYPE_ID
ORDER BY PIZZAS.PRICE DESC 
LIMIT 1;

-- Identify the most common pizza size ordered.

SELECT COUNT(ORDER_DETAILS.ORDER_DETAILS_ID) AS ORDER_COUNT, PIZZAS.SIZE
FROM PIZZAS
LEFT JOIN ORDER_DETAILS
ON PIZZAS.PIZZA_ID = ORDER_DETAILS.PIZZA_ID
GROUP BY PIZZAS.SIZE
ORDER BY ORDER_COUNT DESC;

-- List the top 5 most ordered pizza types along with their quantities.

SELECT PIZZA_TYPES.NAME, SUM(ORDER_DETAILS.QUANTITY) AS QUANTITY
FROM pizza_types
LEFT JOIN PIZZAS
ON PIZZA_TYPES.PIZZA_TYPE_ID = PIZZAS.PIZZA_TYPE_ID
LEFT JOIN ORDER_DETAILS
ON order_details.PIZZA_ID = PIZZAS.PIZZA_ID
GROUP BY PIZZA_TYPES.NAME
ORDER BY QUANTITY DESC
LIMIT 5;